#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi


  if [ -f "$HOME/.config/brew/Brewfile" ]; then
    echo "Updating homebrew bundle"

    # keep in sync with .zshrc
    export HOMEBREW_BUNDLE_FILE_GLOBAL="$HOME/.config/brew/Brewfile"

    brew bundle --global
  fi

fi
