#!/bin/bash

if [ ! -d "$HOME/.oh-my-zsh" ]; then
	echo 'Installing oh-my-zsh'
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# TODO(dkharms): add plugin installation.
